// <auto-generated />
namespace Medical_Store_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createStockTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createStockTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202112090723284_createStockTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
