// <auto-generated />
namespace Medical_Store_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createTestInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createTestInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "202201172055463_createTestInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
