// <auto-generated />
namespace Medical_Store_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeTotalAmountToDefaultValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeTotalAmountToDefaultValue));
        
        string IMigrationMetadata.Id
        {
            get { return "202201122106307_changeTotalAmountToDefaultValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
